notes/urls.py
from django.conf.urls import url

from . import views

app_name = 'notes'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add_note/$', views.add_note, name='add_note'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<pk>.*)/$', views.ShowNote.as_view(), name='show_note'),
]

project_1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^notes/', include('notes.urls')),

]

notes/models.py
from django.db import models


# Create your models here.
class Note(models.Model):
    key = models.CharField(max_length=50, primary_key=True)
    text = models.TextField()

notes/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.urls import reverse
from django.views import generic


from .models import Note


# Create your views here.

class IndexView(TemplateView):
    model = Note
    template_name = 'notes/index.html'


def add_note(request):
    if request.method == "POST":
        key = request.POST['key']

        if key == '':
            return render(request, 'notes/index.html', {'error': 'key cant be empty', })

        text = request.POST['text']
        if text == '':
            return render(request, 'notes/index.html', {'error': 'text cant be empty', })

        note = Note(text=text, key=key)
        note.save()
        return render(request, 'notes/index.html', {'message': 'note add successfully', })

    else:
        return redirect('notes:index')


def search(request):
    if request.method == "POST":
        try:
            selected_note = Note.objects.get(
                pk=request.POST['key']
            )
        except (KeyError, Note.DoesNotExist):
            return render(request, 'notes/index.html', {'error': 'Note doesnt exist', })
        else:
            return HttpResponseRedirect(reverse('notes:show_note',
                                                args=(selected_note.key,)))
    else:
        return redirect('notes:index')


class ShowNote(generic.DetailView):
    model = Note
    template_name = 'notes/show_note.html'

notes/templates/notes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="{% static 'note/code.js' %}"></script>


    <title>Notes</title>
</head>
<body>
    <div class="container">

        <div class="jumbotron">
            <h1>NOTES</h1>
            <p>TODO : write something</p>
        </div>

        {% if message %}
            <!--<div class="modal fade in" id="myModal">-->
                <!--<div class="modal-header">-->
                    <!--<a class="close" data-dismiss="modal">×</a>-->
                    <!--<h3>Modal header</h3>-->
                <!--</div>-->
                <!--<div class="modal-body">-->
                    <!--<p>One fine body…</p>-->
                <!--</div>-->
                <!--<div class="modal-footer">-->
                    <!--<a href="#" class="btn btn-primary">Ok</a>-->
                <!--</div>-->
            <!--</div>-->

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                ...
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>
        {% endif %}

        {% if error %}
        <div class="alert alert-danger alert-dismissable fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Error!</strong> {{error}}.
        </div>
        {% endif %}

        <form action="{% url 'notes:add_note' %}" method="post">
            {% csrf_token %}
            <input type="text" name='key'>
            <input type="text" name='text'>
            <input type="submit" value="Add">
        </form>
        <form action="{% url 'notes:search' %}" method="post">
            {% csrf_token %}
            <input type="text" name='key'>
            <input type="submit" value="search"  class="btn btn-success" >
        </form>
        <textarea>{{text}}</textarea>
    </div>
</body>
</html>

notes/templates/notes/show_note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Note</h1><br>
    <h2>key is : {{note.key}}</h2><br>
    text:<br>
    <textarea>{{note.text}}</textarea>
</body>
</html>